version: '3.9'

services:
  # ========================
  # MySQL
  # ========================
  mysql:
    image: mysql:8.0
    container_name: carbontc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YourStrongRootPassword123!
      MYSQL_DATABASE: Carbon
      MYSQL_USER: carbontc
      MYSQL_PASSWORD: carbontc123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - carbontc_network

  # ========================
  # RabbitMQ
  # ========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: carbontc_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - carbontc_network

  # ========================
  # Auth Service
  # ========================
  auth-service:
    image: vector0001/carbontc-auth-service:latest
    container_name: carbontc_auth_service
    restart: always
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=Carbon;User=root;Password=YourStrongRootPassword123!
      - Jwt__Secret=YourSuperSecretKeyThatIsAtLeast32CharactersLong!
      - Jwt__Issuer=CarbonTC.Auth
      - Jwt__Audience=CarbonTC.Services
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - carbontc_network

  # ========================
  # Gateway Service
  # ========================
  gateway-service:
    image: vector0001/carbontc-gateway-service:latest
    container_name: carbontc_gateway_service
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      - auth-service
    networks:
      - carbontc_network

  # ========================
  # Market Service
  # ========================
  market-service:
    image: vector0001/carbontc-market-service:latest
    container_name: carbontc_market_service
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - carbontc_network

  # ========================
  # Credit Inventory Service
  # ========================
  creditinventory-service:
    image: vector0001/carbontc-creditinventory-service:latest
    container_name: carbontc_creditinventory_service
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - carbontc_network

volumes:
  mysql_data:

networks:
  carbontc_network:
    driver: bridge
