services:
  # ==============================
  # MySQL Database
  # ==============================
  mysql:
    image: mysql:8.0
    container_name: carbontc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 110820               # đổi lại cho khớp Auth Service
      MYSQL_DATABASE: CarbonTC_Auth
      MYSQL_USER: carbontc
      MYSQL_PASSWORD: carbontc123
    ports:
      - "3307:3306"                             # host:container
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - carbontc_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # ==============================
  # RabbitMQ Message Queue
  # ==============================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: carbontc_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI (http://localhost:15672)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - carbontc_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ==============================
  # Auth Service (ASP.NET)
  # ==============================
  auth-service:
    build:
      context: ./CarbonTC.Auth.Service
      dockerfile: Dockerfile
    container_name: carbontc_auth_service
    restart: always
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      # ✅ Kết nối MySQL dùng đúng mật khẩu ở trên
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=CarbonTC_Auth;User=root;Password=110820;

      # JWT config
      - Jwt__Secret=YourSuperSecretKeyThatIsAtLeast32CharactersLong!
      - Jwt__Issuer=CarbonTC.Auth
      - Jwt__Audience=CarbonTC.Services
      - Jwt__ExpirationInMinutes=60
      - Jwt__RefreshTokenExpirationInDays=7

      # RabbitMQ config
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - carbontc_network

# ==============================
# Volumes
# ==============================
volumes:
  mysql_data:
  rabbitmq_data:

# ==============================
# Network
# ==============================
networks:
  carbontc_network:
    driver: bridge
