version: '3.8'

services:
  # 1. RabbitMQ Message Broker (Định nghĩa Credentials)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    environment:
      # KHAI BÁO TÀI KHOẢN MỚI để các Microservice sử dụng
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672" 
      - "15672:15672" 
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservice-net

  # 2. OrderService (Web API + Producer)
  orderservice:
    container_name: orderservice
    build:
      context: . 
      dockerfile: OrderService/Dockerfile 
    environment:
      - RabbitMq:HostName=rabbitmq 
      # CHIA SẺ CREDENTIALS
      - RabbitMq:UserName=admin
      - RabbitMq:Password=admin 
    ports:
      - "8080" # Mở cổng nội bộ
    depends_on:
      rabbitmq:
        condition: service_started  
    networks:
      - microservice-net

  # 3. EmailService (Worker/Consumer)
  emailservice:
    container_name: emailservice
    build:
      context: .
      dockerfile: EmailService/Dockerfile 
    environment:
      - RabbitMq:HostName=rabbitmq
      # CHIA SẺ CREDENTIALS
      - RabbitMq:UserName=admin
      - RabbitMq:Password=admin
    depends_on:
      rabbitmq:
        condition: service_started 
    networks:
      - microservice-net

  # 4. ApiGateway (YARP Reverse Proxy)
  apigateway:
    container_name: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:8080" 
    depends_on:
      - orderservice 
    networks:
      - microservice-net

networks:
  microservice-net:
    driver: bridge