// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
namespace Infrastructure
{
    public partial class CarbonSuggestedPrice
    {
        /// <summary>
        /// model input class for CarbonSuggestedPrice.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(2)]
            [ColumnName(@"CreditType")]
            public string CreditType { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"VerificationStandard")]
            public string VerificationStandard { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Vintage")]
            public float Vintage { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"MarketSupply_SameType")]
            public float MarketSupply_SameType { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"MarketDemand_RecentVolume")]
            public float MarketDemand_RecentVolume { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"PricePerCredit")]
            public float PricePerCredit { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for CarbonSuggestedPrice.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"CreditType")]
            public float[] CreditType { get; set; }

            [ColumnName(@"VerificationStandard")]
            public float[] VerificationStandard { get; set; }

            [ColumnName(@"Vintage")]
            public float Vintage { get; set; }

            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"MarketSupply_SameType")]
            public float MarketSupply_SameType { get; set; }

            [ColumnName(@"MarketDemand_RecentVolume")]
            public float MarketDemand_RecentVolume { get; set; }

            [ColumnName(@"PricePerCredit")]
            public float PricePerCredit { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "CarbonSuggestedPrice.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
